// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0ExNwWBiU9eeWc8OI9j1eDr2zdPt_n0',
    appId: '1:607270501451:web:29c8745d9fe543c58561ce',
    messagingSenderId: '607270501451',
    projectId: 'chat-app-8609f',
    authDomain: 'chat-app-8609f.firebaseapp.com',
    storageBucket: 'chat-app-8609f.appspot.com',
    measurementId: 'G-FV9LKZZHNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhxvJwtNKEfowmh98IVbonq6k8wJoE3o',
    appId: '1:607270501451:android:fca8a2c082b515a78561ce',
    messagingSenderId: '607270501451',
    projectId: 'chat-app-8609f',
    storageBucket: 'chat-app-8609f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVT0skxfKVlc0j0aNDcd9GWiKD0UXSOk',
    appId: '1:607270501451:ios:a95e505fe5b2668a8561ce',
    messagingSenderId: '607270501451',
    projectId: 'chat-app-8609f',
    storageBucket: 'chat-app-8609f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVT0skxfKVlc0j0aNDcd9GWiKD0UXSOk',
    appId: '1:607270501451:ios:a95e505fe5b2668a8561ce',
    messagingSenderId: '607270501451',
    projectId: 'chat-app-8609f',
    storageBucket: 'chat-app-8609f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0ExNwWBiU9eeWc8OI9j1eDr2zdPt_n0',
    appId: '1:607270501451:web:2c6c9fd9e6ecf7938561ce',
    messagingSenderId: '607270501451',
    projectId: 'chat-app-8609f',
    authDomain: 'chat-app-8609f.firebaseapp.com',
    storageBucket: 'chat-app-8609f.appspot.com',
    measurementId: 'G-JHD6YVDLZM',
  );
}
